services:
  - type: redis
    name: Legacy for Family Notifier | Redis
    plan: free
    ipAllowList: []
  - type: cron
    name: Legacy for Family Notifier | Cronjob
    schedule: 0 0 * * *
    buildCommand: NODE_ENV=development yarn install && yarn build
    preDeployCommand: ./bin/run.js authenticate
    startCommand: ./bin/run.js run
    runtime: node
    envVars:
      - key: NODE_ENV
        value: production
      - key: CONFIG
        sync: false