services:
  - type: redis
    name: Legacy for Family Notifier | Redis
    plan: free
  - type: cron
    name: Legacy for Family Notifier | Cronjob
    schedule: "0 0 * * *"
    command: "./bin/run.js run"
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: CONFIG
        sync: false